CREATE TABLE APP_USER(
ID BIGINT AUTO_INCREMENT not null,
SHORT_NAME VARCHAR(5) not null,
PASSWORD VARCHAR(100) not null,
ENABLED BOOLEAN not null,
FIRST_NAME VARCHAR(20) not null,
LAST_NAME VARCHAR(20) not null,
MOD_USER VARCHAR(5) not null,
MOD_TIME TIMESTAMP not null
);