CREATE TABLE CONFIG(
ID BIGINT AUTO_INCREMENT not null,
KEY_NAME VARCHAR(50) not null,
KEY_VALUE VARCHAR(100) not null,
DESCRIPTION VARCHAR(500),
MOD_USER VARCHAR(5) not null,
MOD_TIME TIMESTAMP not null
);