INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (0, 0);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (4, 1);
